image: node:8.4.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run do:coverage
          - npm run do:storybook
          - npm run deploy:website
