name: Lint
on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - reopened
jobs:
  Code-Quality-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: v15.0.1
      - run: npm install -ci
      - run: npm run lint
      - run: npm run test
